import "./../Submodules/WeTransfer-iOS-CI/Fastlane/Fastfile"

desc "Run the tests and prepare for Danger"
lane :test do |options|
  test_project(
    project_name: "WorkflowSample", 
    scheme: "WorkflowSample",
    device: "iPhone 8")
end